name: enzona_payments
description: "Paquete para gestionar sus pagos a través de la pasarela de pagos Enzona."
version: 1.1.0
homepage: https://github.com/Alexgi2002/enzona_payments

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:

  http: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
